---
title: "Dashboard!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(rating, neighbourhood_group, neighbourhood, 
         room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(neighbourhood_group == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Box plot

```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(x = ~price,
          y = ~neighbourhood,
          color = ~neighbourhood,
          type = "box",
          colors = "viridis")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Scatter plot

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: ", price, 
                            "\nNeighborhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers"
  )
```

### Bar chart

```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n )) |>
  plot_ly(x = ~neighbourhood,
          y = ~n,
          type = "bar")
```

