---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots

Today making interactive plots in plotly, using the NYC airbnb dataset

```{r, warning=FALSE,message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Some initial cleaning and subsetting

```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(rating, neighbourhood_group, neighbourhood, 
         room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(neighbourhood_group == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)
```

use plotly

Scatterplot
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: ", price, 
                            "\nNeighborhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers"
  )
```

Boxplot
```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(x = ~price,
          y = ~neighbourhood,
          color = ~neighbourhood,
          type = "box",
          colors = "viridis")
```

Bar chart with number of rentals
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n )) |>
  plot_ly(x = ~neighbourhood,
          y = ~n,
          type = "bar")
```

